project:
  type: website

website:
  title: "Rofikul Masud"
  description: "Developer | Writer | Researcher"
  favicon: images/icon_main.png

  navbar:
    right:
      - text: Articles
        href: articles/articles.qmd
      - text: Publications
        href: publications/publication.qmd
      - text: Blog
        href: blog/blog.qmd

format:
  html:
    theme: flatly
    toc: false


resources:
  - CSS/**
  - images/**
  - resume/**
  - publications/**
  - blog/**
  - about/**
  - books/**
  - articles/**
