project:
  type: website
  output-dir: _site

website:
  title: "Rofikul Masud"
  description: "Developer | Writer | Researcher"
  favicon: images/icon_main_3.png

  navbar:
    right:
      - text: Articles
        href: articles/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Notes
        href: notes/index.qmd
      - text: Books
        href: books/index.qmd




format:
  html:
    page-layout: full
    theme: flatly
    toc: false


resources:
  - CSS/**
  - images/**
  - resume/**
  - publications/**
  - blog/**
  - notes/**
  - books/**
  - articles/**
  - book-covers/**
